var students = [
  {
    "GRE-quantitative": 38,
    "GRE-verbal": 32,
    "GRE-writing": 3.5,
    "GPA": 3.42,
    "Institution-Rank": "Rank 1-100",
    "Rank 1-100": 1,
    "Rank 101-500": 0,
    "Rank 501-1000": 0,
    "Major": "Business",
    "Engineering": 0,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 1,
    "Country": "India",
    "US": 0,
    "China": 0,
    "India": 1,
    "Europe": 0,
    "Diversity-Statement": 2.5,
    "Personal-Statement": 3,
    "RL1": "Average",
    "Strong": 0,
    "Average": 0,
    "Weak": 1,
    "RL2": "Weak",
    "RL3": "Weak",
    "Additional1": 96,
    "Additional2": 27,
    "Additional3": 44,
    "LinearRegression": 339.7639,
    "Acceptance": 100
  },
  {
    "GRE-quantitative": 40,
    "GRE-verbal": 24,
    "GRE-writing": 5,
    "GPA": 3.02,
    "Institution-Rank": "Rank 1-100",
    "Rank 1-100": 1,
    "Rank 101-500": 0,
    "Rank 501-1000": 0,
    "Major": "Natural Science",
    "Engineering": 0,
    "Humanities": 0,
    "Natural Science": 1,
    "Social Science": 0,
    "Business": 0,
    "Country": "US",
    "US": 1,
    "China": 0,
    "India": 0,
    "Europe": 0,
    "Diversity-Statement": 2.5,
    "Personal-Statement": 1.5,
    "RL1": "Average",
    "Strong": 1,
    "Average": 0,
    "Weak": 0,
    "RL2": "Strong",
    "RL3": "Strong",
    "Additional1": 21,
    "Additional2": 20,
    "Additional3": 20,
    "LinearRegression": 290.97725,
    "Acceptance": 0
  },
  {
    "GRE-quantitative": 34,
    "GRE-verbal": 2,
    "GRE-writing": 3.5,
    "GPA": 3.83,
    "Institution-Rank": "Rank 1-100",
    "Rank 1-100": 1,
    "Rank 101-500": 0,
    "Rank 501-1000": 0,
    "Major": "Social Science",
    "Engineering": 0,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 1,
    "Business": 0,
    "Country": "India",
    "US": 0,
    "China": 0,
    "India": 1,
    "Europe": 0,
    "Diversity-Statement": 4.5,
    "Personal-Statement": 5,
    "RL1": "Strong",
    "Strong": 0,
    "Average": 0,
    "Weak": 1,
    "RL2": "Strong",
    "RL3": "Weak",
    "Additional1": 78,
    "Additional2": 55,
    "Additional3": 64,
    "LinearRegression": 443.764,
    "Acceptance": 200
  },
  {
    "GRE-quantitative": 38,
    "GRE-verbal": 24,
    "GRE-writing": 2.5,
    "GPA": 3.6,
    "Institution-Rank": "Rank 1-100",
    "Rank 1-100": 1,
    "Rank 101-500": 0,
    "Rank 501-1000": 0,
    "Major": "Humanities",
    "Engineering": 0,
    "Humanities": 1,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 0,
    "Country": "India",
    "US": 0,
    "China": 0,
    "India": 1,
    "Europe": 0,
    "Diversity-Statement": 3.5,
    "Personal-Statement": 4.5,
    "RL1": "Average",
    "Strong": 0,
    "Average": 0,
    "Weak": 1,
    "RL2": "Average",
    "RL3": "Weak",
    "Additional1": 60,
    "Additional2": 56,
    "Additional3": 62,
    "LinearRegression": 435.6181,
    "Acceptance": 200
  },
  {
    "GRE-quantitative": 36,
    "GRE-verbal": 27,
    "GRE-writing": 4,
    "GPA": 3.29,
    "Institution-Rank": "Rank 101-500",
    "Rank 1-100": 0,
    "Rank 101-500": 1,
    "Rank 501-1000": 0,
    "Major": "Engineering",
    "Engineering": 1,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 0,
    "Country": "China",
    "US": 0,
    "China": 1,
    "India": 0,
    "Europe": 0,
    "Diversity-Statement": 2.5,
    "Personal-Statement": 3,
    "RL1": "Average",
    "Strong": 0,
    "Average": 1,
    "Weak": 0,
    "RL2": "Weak",
    "RL3": "Average",
    "Additional1": 83,
    "Additional2": 3,
    "Additional3": 16,
    "LinearRegression": 241.17035,
    "Acceptance": 0
  },
  {
    "GRE-quantitative": 32,
    "GRE-verbal": 32,
    "GRE-writing": 4.5,
    "GPA": 3.6,
    "Institution-Rank": "Rank 101-500",
    "Rank 1-100": 0,
    "Rank 101-500": 1,
    "Rank 501-1000": 0,
    "Major": "Business",
    "Engineering": 0,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 1,
    "Country": "US",
    "US": 1,
    "China": 0,
    "India": 0,
    "Europe": 0,
    "Diversity-Statement": 3.5,
    "Personal-Statement": 5,
    "RL1": "Weak",
    "Strong": 1,
    "Average": 0,
    "Weak": 0,
    "RL2": "Average",
    "RL3": "Strong",
    "Additional1": 14,
    "Additional2": 38,
    "Additional3": 52,
    "LinearRegression": 400.3514,
    "Acceptance": 100
  },
  {
    "GRE-quantitative": 38,
    "GRE-verbal": 6,
    "GRE-writing": 4.5,
    "GPA": 3.73,
    "Institution-Rank": "Rank 101-500",
    "Rank 1-100": 0,
    "Rank 101-500": 1,
    "Rank 501-1000": 0,
    "Major": "Engineering",
    "Engineering": 1,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 0,
    "Country": "US",
    "US": 1,
    "China": 0,
    "India": 0,
    "Europe": 0,
    "Diversity-Statement": 4,
    "Personal-Statement": 2.5,
    "RL1": "Strong",
    "Strong": 0,
    "Average": 1,
    "Weak": 0,
    "RL2": "Strong",
    "RL3": "Average",
    "Additional1": 68,
    "Additional2": 54,
    "Additional3": 71,
    "LinearRegression": 467.61465,
    "Acceptance": 200
  },
  {
    "GRE-quantitative": 38,
    "GRE-verbal": 31,
    "GRE-writing": 4.5,
    "GPA": 3.6,
    "Institution-Rank": "Rank 101-500",
    "Rank 1-100": 0,
    "Rank 101-500": 1,
    "Rank 501-1000": 0,
    "Major": "Engineering",
    "Engineering": 1,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 0,
    "Country": "China",
    "US": 0,
    "China": 1,
    "India": 0,
    "Europe": 0,
    "Diversity-Statement": 4,
    "Personal-Statement": 3,
    "RL1": "Average",
    "Strong": 0,
    "Average": 1,
    "Weak": 0,
    "RL2": "Strong",
    "RL3": "Average",
    "Additional1": 59,
    "Additional2": 69,
    "Additional3": 66,
    "LinearRegression": 473.17135,
    "Acceptance": 200
  },
  {
    "GRE-quantitative": 40,
    "GRE-verbal": 22,
    "GRE-writing": 1.5,
    "GPA": 3.73,
    "Institution-Rank": "Rank 1-100",
    "Rank 1-100": 1,
    "Rank 101-500": 0,
    "Rank 501-1000": 0,
    "Major": "Humanities",
    "Engineering": 0,
    "Humanities": 1,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 0,
    "Country": "India",
    "US": 0,
    "China": 0,
    "India": 1,
    "Europe": 0,
    "Diversity-Statement": 3.5,
    "Personal-Statement": 4.5,
    "RL1": "Strong",
    "Strong": 0,
    "Average": 1,
    "Weak": 0,
    "RL2": "Strong",
    "RL3": "Average",
    "Additional1": 68,
    "Additional2": 71,
    "Additional3": 93,
    "LinearRegression": 528.3317,
    "Acceptance": 300
  },
  {
    "GRE-quantitative": 33,
    "GRE-verbal": 29,
    "GRE-writing": 3.5,
    "GPA": 3.63,
    "Institution-Rank": "Rank 101-500",
    "Rank 1-100": 0,
    "Rank 101-500": 1,
    "Rank 501-1000": 0,
    "Major": "Engineering",
    "Engineering": 1,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 0,
    "Country": "US",
    "US": 1,
    "China": 0,
    "India": 0,
    "Europe": 0,
    "Diversity-Statement": 3.5,
    "Personal-Statement": 5,
    "RL1": "Strong",
    "Strong": 0,
    "Average": 1,
    "Weak": 0,
    "RL2": "Weak",
    "RL3": "Average",
    "Additional1": 46,
    "Additional2": 36,
    "Additional3": 51,
    "LinearRegression": 384.5866,
    "Acceptance": 100
  },
  {
    "GRE-quantitative": 27,
    "GRE-verbal": 30,
    "GRE-writing": 3.5,
    "GPA": 3.61,
    "Institution-Rank": "Rank 101-500",
    "Rank 1-100": 0,
    "Rank 101-500": 1,
    "Rank 501-1000": 0,
    "Major": "Business",
    "Engineering": 0,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 1,
    "Country": "Europe",
    "US": 0,
    "China": 0,
    "India": 0,
    "Europe": 1,
    "Diversity-Statement": 3.5,
    "Personal-Statement": 3,
    "RL1": "Average",
    "Strong": 1,
    "Average": 0,
    "Weak": 0,
    "RL2": "Weak",
    "RL3": "Strong",
    "Additional1": 79,
    "Additional2": 28,
    "Additional3": 53,
    "LinearRegression": 357.1351,
    "Acceptance": 100
  },
  {
    "GRE-quantitative": 39,
    "GRE-verbal": 23,
    "GRE-writing": 5,
    "GPA": 3.84,
    "Institution-Rank": "Rank 101-500",
    "Rank 1-100": 0,
    "Rank 101-500": 1,
    "Rank 501-1000": 0,
    "Major": "Engineering",
    "Engineering": 1,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 0,
    "Country": "China",
    "US": 0,
    "China": 1,
    "India": 0,
    "Europe": 0,
    "Diversity-Statement": 4.5,
    "Personal-Statement": 5,
    "RL1": "Average",
    "Strong": 0,
    "Average": 0,
    "Weak": 1,
    "RL2": "Weak",
    "RL3": "Weak",
    "Additional1": 15,
    "Additional2": 65,
    "Additional3": 73,
    "LinearRegression": 477.04675,
    "Acceptance": 200
  },
  {
    "GRE-quantitative": 18,
    "GRE-verbal": 9,
    "GRE-writing": 5,
    "GPA": 3.77,
    "Institution-Rank": "Rank 1-100",
    "Rank 1-100": 1,
    "Rank 101-500": 0,
    "Rank 501-1000": 0,
    "Major": "Engineering",
    "Engineering": 1,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 0,
    "Country": "China",
    "US": 0,
    "China": 1,
    "India": 0,
    "Europe": 0,
    "Diversity-Statement": 4.5,
    "Personal-Statement": 4.5,
    "RL1": "Weak",
    "Strong": 0,
    "Average": 1,
    "Weak": 0,
    "RL2": "Weak",
    "RL3": "Average",
    "Additional1": 45,
    "Additional2": 3,
    "Additional3": 1,
    "LinearRegression": 233.09265,
    "Acceptance": 0
  },
  {
    "GRE-quantitative": 39,
    "GRE-verbal": 21,
    "GRE-writing": 3.5,
    "GPA": 3.24,
    "Institution-Rank": "Rank 101-500",
    "Rank 1-100": 0,
    "Rank 101-500": 1,
    "Rank 501-1000": 0,
    "Major": "Business",
    "Engineering": 0,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 1,
    "Country": "Europe",
    "US": 0,
    "China": 0,
    "India": 0,
    "Europe": 1,
    "Diversity-Statement": 3.5,
    "Personal-Statement": 5,
    "RL1": "Strong",
    "Strong": 1,
    "Average": 0,
    "Weak": 0,
    "RL2": "Average",
    "RL3": "Strong",
    "Additional1": 30,
    "Additional2": 12,
    "Additional3": 28,
    "LinearRegression": 284.9636,
    "Acceptance": 0
  },
  {
    "GRE-quantitative": 21,
    "GRE-verbal": 33,
    "GRE-writing": 4,
    "GPA": 3.72,
    "Institution-Rank": "Rank 101-500",
    "Rank 1-100": 0,
    "Rank 101-500": 1,
    "Rank 501-1000": 0,
    "Major": "Engineering",
    "Engineering": 1,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 0,
    "Country": "India",
    "US": 0,
    "China": 0,
    "India": 1,
    "Europe": 0,
    "Diversity-Statement": 2,
    "Personal-Statement": 3,
    "RL1": "Average",
    "Strong": 0,
    "Average": 1,
    "Weak": 0,
    "RL2": "Strong",
    "RL3": "Average",
    "Additional1": 67,
    "Additional2": 38,
    "Additional3": 56,
    "LinearRegression": 378.5363,
    "Acceptance": 100
  },
  {
    "GRE-quantitative": 38,
    "GRE-verbal": 26,
    "GRE-writing": 1,
    "GPA": 3.67,
    "Institution-Rank": "Rank 1-100",
    "Rank 1-100": 1,
    "Rank 101-500": 0,
    "Rank 501-1000": 0,
    "Major": "Humanities",
    "Engineering": 0,
    "Humanities": 1,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 0,
    "Country": "US",
    "US": 1,
    "China": 0,
    "India": 0,
    "Europe": 0,
    "Diversity-Statement": 3.5,
    "Personal-Statement": 4.5,
    "RL1": "Average",
    "Strong": 0,
    "Average": 0,
    "Weak": 1,
    "RL2": "Weak",
    "RL3": "Weak",
    "Additional1": 77,
    "Additional2": 55,
    "Additional3": 67,
    "LinearRegression": 455.85795,
    "Acceptance": 200
  },
  {
    "GRE-quantitative": 35,
    "GRE-verbal": 25,
    "GRE-writing": 3.5,
    "GPA": 3.72,
    "Institution-Rank": "Rank 1-100",
    "Rank 1-100": 1,
    "Rank 101-500": 0,
    "Rank 501-1000": 0,
    "Major": "Engineering",
    "Engineering": 1,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 0,
    "Country": "Europe",
    "US": 0,
    "China": 0,
    "India": 0,
    "Europe": 1,
    "Diversity-Statement": 3.5,
    "Personal-Statement": 4.5,
    "RL1": "Weak",
    "Strong": 1,
    "Average": 0,
    "Weak": 0,
    "RL2": "Strong",
    "RL3": "Strong",
    "Additional1": 94,
    "Additional2": 61,
    "Additional3": 77,
    "LinearRegression": 481.2256,
    "Acceptance": 200
  },
  {
    "GRE-quantitative": 38,
    "GRE-verbal": 22,
    "GRE-writing": 4,
    "GPA": 3.58,
    "Institution-Rank": "Rank 1-100",
    "Rank 1-100": 1,
    "Rank 101-500": 0,
    "Rank 501-1000": 0,
    "Major": "Business",
    "Engineering": 0,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 1,
    "Country": "US",
    "US": 1,
    "China": 0,
    "India": 0,
    "Europe": 0,
    "Diversity-Statement": 4.5,
    "Personal-Statement": 5,
    "RL1": "Weak",
    "Strong": 0,
    "Average": 0,
    "Weak": 1,
    "RL2": "Weak",
    "RL3": "Weak",
    "Additional1": 49,
    "Additional2": 58,
    "Additional3": 68,
    "LinearRegression": 468.55485,
    "Acceptance": 200
  },
  {
    "GRE-quantitative": 40,
    "GRE-verbal": 13,
    "GRE-writing": 4.5,
    "GPA": 3.4,
    "Institution-Rank": "Rank 1-100",
    "Rank 1-100": 1,
    "Rank 101-500": 0,
    "Rank 501-1000": 0,
    "Major": "Engineering",
    "Engineering": 1,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 0,
    "Country": "China",
    "US": 0,
    "China": 1,
    "India": 0,
    "Europe": 0,
    "Diversity-Statement": 4.5,
    "Personal-Statement": 3,
    "RL1": "Strong",
    "Strong": 0,
    "Average": 1,
    "Weak": 0,
    "RL2": "Strong",
    "RL3": "Average",
    "Additional1": 9,
    "Additional2": 30,
    "Additional3": 55,
    "LinearRegression": 381.997,
    "Acceptance": 100
  },
  {
    "GRE-quantitative": 38,
    "GRE-verbal": 28,
    "GRE-writing": 2,
    "GPA": 3.59,
    "Institution-Rank": "Rank 1-100",
    "Rank 1-100": 1,
    "Rank 101-500": 0,
    "Rank 501-1000": 0,
    "Major": "Engineering",
    "Engineering": 1,
    "Humanities": 0,
    "Natural Science": 0,
    "Social Science": 0,
    "Business": 0,
    "Country": "India",
    "US": 0,
    "China": 0,
    "India": 1,
    "Europe": 0,
    "Diversity-Statement": 4,
    "Personal-Statement": 3,
    "RL1": "Weak",
    "Strong": 0,
    "Average": 0,
    "Weak": 1,
    "RL2": "Weak",
    "RL3": "Weak",
    "Additional1": 15,
    "Additional2": 32,
    "Additional3": 56,
    "LinearRegression": 377.3525,
    "Acceptance": 100
  }
];
