var students = [
  {
    "GRE-Verbal": 8,
    "GRE-Quantitative": 37,
    "GRE-Writing": 4,
    "GPA": 3.34,
    "Institution Rank": "Rank 101-500",
    "Undergraduate Major": "Business",
    "Country": "India",
    "Statement of Purpose": 2.5,
    "Diversity Statement": 3,
    "Letter of Recommendation #1": "Strong",
    "Letter of Recommendation #2": "Weak",
    "Letter of Recommendation #3": "Strong",
    "Additional Attribute 1": 61,
    "Additional Attribute 2": 9,
    "Additional Attribute 3": 90,
    "LinearRegression": 235.74595,
    "Acceptance": 0
  },
  {
    "GRE-Verbal": 20,
    "GRE-Quantitative": 38,
    "GRE-Writing": 3.5,
    "GPA": 3.57,
    "Institution Rank": "Rank 1-100",
    "Undergraduate Major": "Social Science",
    "Country": "Europe",
    "Statement of Purpose": 2,
    "Diversity Statement": 3,
    "Letter of Recommendation #1": "Weak",
    "Letter of Recommendation #2": "Average",
    "Letter of Recommendation #3": "Strong",
    "Additional Attribute 1": 24,
    "Additional Attribute 2": 24,
    "Additional Attribute 3": 63,
    "LinearRegression": 325.81285,
    "Acceptance": 1
  },
  {
    "GRE-Verbal": 34,
    "GRE-Quantitative": 30,
    "GRE-Writing": 4,
    "GPA": 3.8,
    "Institution Rank": "Rank 1-100",
    "Undergraduate Major": "Social Science",
    "Country": "US",
    "Statement of Purpose": 2.5,
    "Diversity Statement": 4.5,
    "Letter of Recommendation #1": "Strong",
    "Letter of Recommendation #2": "Strong",
    "Letter of Recommendation #3": "Average",
    "Additional Attribute 1": 55,
    "Additional Attribute 2": 43,
    "Additional Attribute 3": 31,
    "LinearRegression": 438.88175,
    "Acceptance": 3
  },
  {
    "GRE-Verbal": 29,
    "GRE-Quantitative": 38,
    "GRE-Writing": 2.5,
    "GPA": 4,
    "Institution Rank": "Rank 101-500",
    "Undergraduate Major": "Social Science",
    "Country": "China",
    "Statement of Purpose": 3.5,
    "Diversity Statement": 3,
    "Letter of Recommendation #1": "Average",
    "Letter of Recommendation #2": "Average",
    "Letter of Recommendation #3": "Weak",
    "Additional Attribute 1": 91,
    "Additional Attribute 2": 74,
    "Additional Attribute 3": 7,
    "LinearRegression": 527.417,
    "Acceptance": 4
  },
  {
    "GRE-Verbal": 21,
    "GRE-Quantitative": 39,
    "GRE-Writing": 3.5,
    "GPA": 3.24,
    "Institution Rank": "Rank 101-500",
    "Undergraduate Major": "Business",
    "Country": "Europe",
    "Statement of Purpose": 3.5,
    "Diversity Statement": 5,
    "Letter of Recommendation #1": "Strong",
    "Letter of Recommendation #2": "Average",
    "Letter of Recommendation #3": "Strong",
    "Additional Attribute 1": 30,
    "Additional Attribute 2": 1,
    "Additional Attribute 3": 96,
    "LinearRegression": 225.7643,
    "Acceptance": 0
  },
  {
    "GRE-Verbal": 28,
    "GRE-Quantitative": 28,
    "GRE-Writing": 4.5,
    "GPA": 3.66,
    "Institution Rank": "Rank 101-500",
    "Undergraduate Major": "Business",
    "Country": "China",
    "Statement of Purpose": 2,
    "Diversity Statement": 4.5,
    "Letter of Recommendation #1": "Strong",
    "Letter of Recommendation #2": "Average",
    "Letter of Recommendation #3": "Weak",
    "Additional Attribute 1": 0,
    "Additional Attribute 2": 24,
    "Additional Attribute 3": 60,
    "LinearRegression": 331.10395,
    "Acceptance": 1
  },
  {
    "GRE-Verbal": 11,
    "GRE-Quantitative": 39,
    "GRE-Writing": 3.5,
    "GPA": 3.58,
    "Institution Rank": "Rank 1-100",
    "Undergraduate Major": "Humanities",
    "Country": "US",
    "Statement of Purpose": 3.5,
    "Diversity Statement": 4.5,
    "Letter of Recommendation #1": "Strong",
    "Letter of Recommendation #2": "Average",
    "Letter of Recommendation #3": "Average",
    "Additional Attribute 1": 72,
    "Additional Attribute 2": 43,
    "Additional Attribute 3": 40,
    "LinearRegression": 424.7709,
    "Acceptance": 2
  },
  {
    "GRE-Verbal": 36,
    "GRE-Quantitative": 39,
    "GRE-Writing": 3.5,
    "GPA": 3.78,
    "Institution Rank": "Rank 101-500",
    "Undergraduate Major": "Humanities",
    "Country": "US",
    "Statement of Purpose": 4,
    "Diversity Statement": 3,
    "Letter of Recommendation #1": "Average",
    "Letter of Recommendation #2": "Weak",
    "Letter of Recommendation #3": "Strong",
    "Additional Attribute 1": 37,
    "Additional Attribute 2": 92,
    "Additional Attribute 3": 6,
    "LinearRegression": 571.08955,
    "Acceptance": 3
  },
  {
    "GRE-Verbal": 24,
    "GRE-Quantitative": 40,
    "GRE-Writing": 5,
    "GPA": 3.02,
    "Institution Rank": "Rank 1-100",
    "Undergraduate Major": "Natural Science",
    "Country": "US",
    "Statement of Purpose": 2.5,
    "Diversity Statement": 1.5,
    "Letter of Recommendation #1": "Average",
    "Letter of Recommendation #2": "Strong",
    "Letter of Recommendation #3": "Strong",
    "Additional Attribute 1": 21,
    "Additional Attribute 2": 18,
    "Additional Attribute 3": 78,
    "LinearRegression": 293.31525,
    "Acceptance": 0
  },
  {
    "GRE-Verbal": 28,
    "GRE-Quantitative": 26,
    "GRE-Writing": 5,
    "GPA": 3.53,
    "Institution Rank": "Rank 101-500",
    "Undergraduate Major": "Humanities",
    "Country": "India",
    "Statement of Purpose": 4.5,
    "Diversity Statement": 4.5,
    "Letter of Recommendation #1": "Average",
    "Letter of Recommendation #2": "Weak",
    "Letter of Recommendation #3": "Weak",
    "Additional Attribute 1": 47,
    "Additional Attribute 2": 28,
    "Additional Attribute 3": 65,
    "LinearRegression": 323.51675,
    "Acceptance": 1
  },
  {
    "GRE-Verbal": 30,
    "GRE-Quantitative": 35,
    "GRE-Writing": 3.5,
    "GPA": 3.6,
    "Institution Rank": "Rank 101-500",
    "Undergraduate Major": "Business",
    "Country": "China",
    "Statement of Purpose": 2.5,
    "Diversity Statement": 4.5,
    "Letter of Recommendation #1": "Strong",
    "Letter of Recommendation #2": "Strong",
    "Letter of Recommendation #3": "Average",
    "Additional Attribute 1": 98,
    "Additional Attribute 2": 59,
    "Additional Attribute 3": 24,
    "LinearRegression": 464.6707,
    "Acceptance": 2
  },
  {
    "GRE-Verbal": 26,
    "GRE-Quantitative": 39,
    "GRE-Writing": 5,
    "GPA": 3.74,
    "Institution Rank": "Rank 1-100",
    "Undergraduate Major": "Business",
    "Country": "China",
    "Statement of Purpose": 3.5,
    "Diversity Statement": 5,
    "Letter of Recommendation #1": "Strong",
    "Letter of Recommendation #2": "Average",
    "Letter of Recommendation #3": "Strong",
    "Additional Attribute 1": 21,
    "Additional Attribute 2": 96,
    "Additional Attribute 3": 17,
    "LinearRegression": 554.80045,
    "Acceptance": 3
  },
  {
    "GRE-Verbal": 4,
    "GRE-Quantitative": 32,
    "GRE-Writing": 3.5,
    "GPA": 3.38,
    "Institution Rank": "Rank 101-500",
    "Undergraduate Major": "Engineering",
    "Country": "Europe",
    "Statement of Purpose": 4,
    "Diversity Statement": 3,
    "Letter of Recommendation #1": "Strong",
    "Letter of Recommendation #2": "Weak",
    "Letter of Recommendation #3": "Strong",
    "Additional Attribute 1": 88,
    "Additional Attribute 2": 5,
    "Additional Attribute 3": 90,
    "LinearRegression": 227.97765,
    "Acceptance": 0
  },
  {
    "GRE-Verbal": 27,
    "GRE-Quantitative": 26,
    "GRE-Writing": 4,
    "GPA": 3.81,
    "Institution Rank": "Rank 1-100",
    "Undergraduate Major": "Engineering",
    "Country": "China",
    "Statement of Purpose": 3.5,
    "Diversity Statement": 2.5,
    "Letter of Recommendation #1": "Weak",
    "Letter of Recommendation #2": "Weak",
    "Letter of Recommendation #3": "Weak",
    "Additional Attribute 1": 10,
    "Additional Attribute 2": 31,
    "Additional Attribute 3": 69,
    "LinearRegression": 334.54005,
    "Acceptance": 1
  },
  {
    "GRE-Verbal": 21,
    "GRE-Quantitative": 40,
    "GRE-Writing": 3.5,
    "GPA": 3.74,
    "Institution Rank": "Rank 1-100",
    "Undergraduate Major": "Humanities",
    "Country": "Europe",
    "Statement of Purpose": 3,
    "Diversity Statement": 1,
    "Letter of Recommendation #1": "Weak",
    "Letter of Recommendation #2": "Strong",
    "Letter of Recommendation #3": "Average",
    "Additional Attribute 1": 57,
    "Additional Attribute 2": 65,
    "Additional Attribute 3": 31,
    "LinearRegression": 474.58365,
    "Acceptance": 2
  },
  {
    "GRE-Verbal": 22,
    "GRE-Quantitative": 40,
    "GRE-Writing": 1.5,
    "GPA": 3.73,
    "Institution Rank": "Rank 1-100",
    "Undergraduate Major": "Humanities",
    "Country": "India",
    "Statement of Purpose": 3.5,
    "Diversity Statement": 4.5,
    "Letter of Recommendation #1": "Strong",
    "Letter of Recommendation #2": "Strong",
    "Letter of Recommendation #3": "Average",
    "Additional Attribute 1": 68,
    "Additional Attribute 2": 81,
    "Additional Attribute 3": 12,
    "LinearRegression": 535.116,
    "Acceptance": 3
  },
  {
    "GRE-Verbal": 25,
    "GRE-Quantitative": 32,
    "GRE-Writing": 5,
    "GPA": 3.38,
    "Institution Rank": "Rank 1-100",
    "Undergraduate Major": "Engineering",
    "Country": "Europe",
    "Statement of Purpose": 3,
    "Diversity Statement": 2.5,
    "Letter of Recommendation #1": "Strong",
    "Letter of Recommendation #2": "Average",
    "Letter of Recommendation #3": "Strong",
    "Additional Attribute 1": 31,
    "Additional Attribute 2": 7,
    "Additional Attribute 3": 97,
    "LinearRegression": 228.8029,
    "Acceptance": 0
  },
  {
    "GRE-Verbal": 9,
    "GRE-Quantitative": 39,
    "GRE-Writing": 3,
    "GPA": 3.66,
    "Institution Rank": "Rank 101-500",
    "Undergraduate Major": "Social Science",
    "Country": "India",
    "Statement of Purpose": 4,
    "Diversity Statement": 4.5,
    "Letter of Recommendation #1": "Weak",
    "Letter of Recommendation #2": "Average",
    "Letter of Recommendation #3": "Strong",
    "Additional Attribute 1": 95,
    "Additional Attribute 2": 28,
    "Additional Attribute 3": 63,
    "LinearRegression": 340.1077,
    "Acceptance": 1
  },
  {
    "GRE-Verbal": 22,
    "GRE-Quantitative": 35,
    "GRE-Writing": 4,
    "GPA": 3.81,
    "Institution Rank": "Rank 1-100",
    "Undergraduate Major": "Engineering",
    "Country": "Europe",
    "Statement of Purpose": 3.5,
    "Diversity Statement": 4.5,
    "Letter of Recommendation #1": "Weak",
    "Letter of Recommendation #2": "Strong",
    "Letter of Recommendation #3": "Weak",
    "Additional Attribute 1": 97,
    "Additional Attribute 2": 40,
    "Additional Attribute 3": 28,
    "LinearRegression": 435.10215,
    "Acceptance": 2
  },
  {
    "GRE-Verbal": 23,
    "GRE-Quantitative": 39,
    "GRE-Writing": 4,
    "GPA": 3.92,
    "Institution Rank": "Rank 101-500",
    "Undergraduate Major": "Business",
    "Country": "Europe",
    "Statement of Purpose": 4,
    "Diversity Statement": 4.5,
    "Letter of Recommendation #1": "Weak",
    "Letter of Recommendation #2": "Average",
    "Letter of Recommendation #3": "Strong",
    "Additional Attribute 1": 73,
    "Additional Attribute 2": 99,
    "Additional Attribute 3": 6,
    "LinearRegression": 582.063,
    "Acceptance": 3
  }
]
